export const deals = [
	{
		corporateUsername: "corporate1",
		industryName: "Technology",
		companyName: "CloudSync Technologies",
		description: "Cloud infrastructure and SaaS platform.",
		expectedROI: 18,
		riskLevel: "LOW",
		riskScore: 25,
		minInvestment: 50000,
		maxInvestment: 500000,
		targetAmount: 5000000,
		currentRaisedAmount: 0,
		dealStatus: "OPEN",
		closingDate: "2026-12-31",
		tags: ["Cloud", "SaaS"],
	},

	{
		corporateUsername: "corporate1",
		industryName: "AI",
		companyName: "VisionAI Labs",
		description: "AI-powered computer vision platform.",
		expectedROI: 30,
		riskLevel: "HIGH",
		riskScore: 75,
		minInvestment: 100000,
		maxInvestment: 1000000,
		targetAmount: 10000000,
		currentRaisedAmount: 0,
		dealStatus: "OPEN",
		closingDate: "2026-11-30",
		tags: ["AI", "Computer Vision"],
	},
];
