export const investorPreferences = [
	{
		username: "investor1",
		riskAppetite: "LOW",
		minBudget: 50000,
		maxBudget: 200000,
		industries: ["Technology", "Education"],
	},
	{
		username: "investor2",
		riskAppetite: "MEDIUM",
		minBudget: 100000,
		maxBudget: 500000,
		industries: ["AI", "Fintech"],
	},
	{
		username: "investor3",
		riskAppetite: "HIGH",
		minBudget: 250000,
		maxBudget: 1000000,
		industries: ["AI", "Fintech", "E-Commerce"],
	},
	{
		username: "investor4",
		riskAppetite: "LOW",
		minBudget: 25000,
		maxBudget: 150000,
		industries: ["Healthcare", "Education"],
	},
	{
		username: "investor5",
		riskAppetite: "MEDIUM",
		minBudget: 100000,
		maxBudget: 750000,
		industries: ["Technology", "AI", "Energy"],
	},
	{
		username: "investor6",
		riskAppetite: "HIGH",
		minBudget: 500000,
		maxBudget: 2000000,
		industries: ["Real Estate", "Energy"],
	},
	{
		username: "investor7",
		riskAppetite: "MEDIUM",
		minBudget: 150000,
		maxBudget: 800000,
		industries: ["Fintech", "E-Commerce"],
	},
	{
		username: "investor8",
		riskAppetite: "LOW",
		minBudget: 50000,
		maxBudget: 300000,
		industries: ["Agriculture", "Energy"],
	},
	{
		username: "investor9",
		riskAppetite: "HIGH",
		minBudget: 300000,
		maxBudget: 1500000,
		industries: ["AI", "Manufacturing"],
	},
	{
		username: "investor10",
		riskAppetite: "MEDIUM",
		minBudget: 100000,
		maxBudget: 600000,
		industries: ["Technology", "Healthcare", "Education"],
	},
];
