export const AdminUser = {
	name: "System Admin",
	email: "admin@dealflow.com",
	username: "admin",
	password: "Admin@123",
	role: "ADMIN",
};

export const CorporateUsers = [
	{
		name: "Tech Ventures Pvt Ltd",
		email: "corporate1@dealflow.com",
		username: "corporate1",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "Innovate Capital",
		email: "corporate2@dealflow.com",
		username: "corporate2",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "Future Growth Ventures",
		email: "corporate3@dealflow.com",
		username: "corporate3",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "NextGen Holdings",
		email: "corporate4@dealflow.com",
		username: "corporate4",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "Smart Investments Ltd",
		email: "corporate5@dealflow.com",
		username: "corporate5",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "Green Energy Corp",
		email: "corporate6@dealflow.com",
		username: "corporate6",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "HealthTech Ventures",
		email: "corporate7@dealflow.com",
		username: "corporate7",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "FinEdge Capital",
		email: "corporate8@dealflow.com",
		username: "corporate8",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "EduFuture Pvt Ltd",
		email: "corporate9@dealflow.com",
		username: "corporate9",
		password: "Corporate@123",
		role: "CORPORATE",
	},
	{
		name: "AgriGrowth Solutions",
		email: "corporate10@dealflow.com",
		username: "corporate10",
		password: "Corporate@123",
		role: "CORPORATE",
	},
];

export const InvestorUsers = [
	{
		name: "John Investor",
		email: "investor1@dealflow.com",
		username: "investor1",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "Alice Johnson",
		email: "investor2@dealflow.com",
		username: "investor2",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "Michael Smith",
		email: "investor3@dealflow.com",
		username: "investor3",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "Sophia Brown",
		email: "investor4@dealflow.com",
		username: "investor4",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "David Wilson",
		email: "investor5@dealflow.com",
		username: "investor5",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "Emma Davis",
		email: "investor6@dealflow.com",
		username: "investor6",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "James Taylor",
		email: "investor7@dealflow.com",
		username: "investor7",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "Olivia Thomas",
		email: "investor8@dealflow.com",
		username: "investor8",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "William Anderson",
		email: "investor9@dealflow.com",
		username: "investor9",
		password: "Investor@123",
		role: "INVESTOR",
	},
	{
		name: "Ava Martinez",
		email: "investor10@dealflow.com",
		username: "investor10",
		password: "Investor@123",
		role: "INVESTOR",
	},
];
