@url = http://localhost:3000/analytics
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4MDY1NTUxMCwiZXhwIjoxNzgwNzQxOTEwfQ.NiskPYi21ORIi57YPM6aLDZhWjEAQY2y_4BtBy7KNFA

### Dashbaord
GET {{url}}/dashboard
Authorization: {{token}}
Content-Type: application/json

### Trends
GET {{url}}/trends
Authorization: {{token}}
Content-Type: application/json


### Corporate
GET {{url}}/corporate
Authorization: {{token}}
Content-Type: application/json


### Investor
GET {{url}}/investor
Authorization: {{token}}
Content-Type: application/json

