@url = http://localhost:3000/investor-preference
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJuYW1lIjoiaW52ZXN0b3IyIiwicm9sZSI6IklOVkVTVE9SIiwiaWF0IjoxNzgwNjU0NDQ5LCJleHAiOjE3ODA3NDA4NDl9.H7jvhvETxA-_UBophEUlo2s9dzfBgUqn31vwmThL4K0

### Get Preference
GET {{url}}
Authorization: {{token}}

###

### Create Preference
POST {{url}}
Authorization: {{token}}
Content-Type: application/json

{
	"riskAppetite": "MEDIUM",
	"minBudget": 50000,
	"maxBudget": 500000
}

###
PUT {{url}}
Authorization: {{token}}
Content-Type: application/json

{
	"riskAppetite": "LOW",
	"minBudget": 50000,
	"maxBudget": 500000,
	"industryIds": [1, 2, 3]
}
###

### Update Preference
PUT {{url}}
Authorization: {{token}}
Content-Type: application/json

{
	"riskAppetite": "HIGH",
	"minBudget": 100000,
	"maxBudget": 1000000
}
