@url = http://localhost:3000/investor-preference
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJpbnZlc3RvciIsInJvbGUiOiJJTlZFU1RPUiIsImlhdCI6MTc4MDYxMjY4MywiZXhwIjoxNzgwNjk5MDgzfQ.5ahiFEEZ2dpDrmxpdRqmHL2Id2YZ0-LLkpbbT-4LgtI

### Get Preference
GET {{url}}
Authorization: {{token}}

###

### Create Preference
POST {{url}}
Authorization: {{token}}
Content-Type: application/json

{
	"riskAppetite": "MEDIUM",
	"minBudget": 50000,
	"maxBudget": 500000
}

###
PUT {{url}}
Authorization: {{token}}
Content-Type: application/json

{
	"riskAppetite": "LOW",
	"minBudget": 50000,
	"maxBudget": 500000,
	"industryIds": [1, 2, 3]
}
###

### Update Preference
PUT {{url}}
Authorization: {{token}}
Content-Type: application/json

{
	"riskAppetite": "HIGH",
	"minBudget": 100000,
	"maxBudget": 1000000
}
