@url = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4MDYxMTQ0OCwiZXhwIjoxNzgwNjk3ODQ4fQ.NDHwWGwIwIofJQAqBk5kzl82U75qBqQEZngIAvDtZIw

### Get all users
GET {{url}}/user?status=1&role=INVESTOR
Authorization: {{token}}
Content-Type: application/json


###


### Get all users
GET {{url}}/user/search/records
Authorization: {{token}}
Content-Type: application/json


###


### Get a specific user by ID
GET {{url}}/user/20
Authorization: {{token}}
Content-Type: application/json


###


### Create a new user
POST {{url}}/user
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Omn Shinde",
  "username": "omnath3",
  "password": "12345",
  "employeeId": "2236",
  "roleId": 2,
  "siteId": null
}


###


### Update a user
PUT {{url}}/user/47
Authorization: {{token}}
Content-Type: application/json

{
  "username": "omnath12",
  "password": "12345",
  "siteId": 1
}



### Delete a user
DELETE {{url}}/user/3
Authorization: {{token}}
Content-Type: application/json

### Restore a user
PATCH  {{url}}/user/3
Authorization: {{token}}
Content-Type: application/json


